/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Parking;
import javax.swing.ImageIcon;
import java.awt.Image;

import javax.swing.JOptionPane;
 
 import java.text.SimpleDateFormat;
 import java.util.Date;
//import java.io.IOException;
//import java.lang.InterruptedException;


/**
 *
 * @author hp
 */
public class UGParking extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form UGParking
     */
    Parking myparking;
    public UGParking() {
        myparking=new Parking(2);
        initComponents();
        setImage("C:\\parking.png");
        
        
        
    }
    @Override
    public void run(){
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImgLabel = new javax.swing.JLabel();
        entbtn = new javax.swing.JButton();
        LabelTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entbtn.setBackground(new java.awt.Color(0, 51, 255));
        entbtn.setForeground(new java.awt.Color(255, 255, 255));
        entbtn.setText("Entrer");
        entbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entbtnActionPerformed(evt);
            }
        });

        LabelTxt.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        LabelTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTxt.setText("PARKING");
        LabelTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(LabelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(entbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ImgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(entbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    private void entbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entbtnActionPerformed
         // TODO add your handling code here:
         Voiture voiture;
         String nom;
         Integer temps;
         nom=JOptionPane.showInputDialog(this, "Veuillez enter le nom de voiture", "nom",JOptionPane.PLAIN_MESSAGE);
         
         temps=Integer.parseInt(JOptionPane.showInputDialog(this, "Veuillez enter le temps", "temps",JOptionPane.PLAIN_MESSAGE));
         voiture=new Voiture(nom,myparking,temps,this);
         //SimpleDateFormat timeRef=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
         //Date date=new Date();
         //System.out.println(timeRef.format(date));
         Thread mytread=new Thread(voiture);
         mytread.start();
         
        
        
    }//GEN-LAST:event_entbtnActionPerformed
    public void setImage(String chemin){
    ImageIcon icon= new ImageIcon(chemin);
    Image img=icon.getImage();
    Image imgScale=img.getScaledInstance(ImgLabel.getWidth(), ImgLabel.getHeight(), Image.SCALE_SMOOTH);
    ImageIcon scaleIcon=new ImageIcon(imgScale);
    ImgLabel.setIcon(icon);
    
    
    }
    public void setText(String title){
    LabelTxt.setText(title);
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UGParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UGParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UGParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UGParking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UGParking p=new UGParking();
                p.setVisible(true);
                p.setTitle("LA gestion parking");
                p.setLocationRelativeTo(null);}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImgLabel;
    private javax.swing.JLabel LabelTxt;
    private javax.swing.JButton entbtn;
    // End of variables declaration//GEN-END:variables
}
